config/routes.rb
Rails.application.routes.draw do
  root to: 'categories#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :categories, except: %i[edit update] do
  resources :bookmarks, only: %i[new create]
  end
  resources :bookmarks, only: %i[destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :recipe
  belongs_to :category

  validates :comment, presence: true, length: { minimum: 6, too_short: 'must have at least 6 characters' }
  validates :recipe_id, uniqueness: { scope: :category_id}
end

app/models/category.rb
class Category < ApplicationRecord
  has_one_attached :photo
  has_many :bookmarks, dependent: :destroy
  has_many :recipes, through: :bookmarks

  validates :name, presence: true, uniqueness: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :bookmarks

  validates :description, presence: true
  validates :name, presence: true, uniqueness: true
  validates :rating, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_category, only: %i[new create]
  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = @category.bookmarks.new(bookmark_params)
    @bookmark.category = @category

    if @bookmark.save
      redirect_to category_path(@category)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to category_path(@bookmark.category)
  end

  private

  def set_category
    @category = Category.find(params[:category_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:recipe_id, :comment)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show destroy]

  def index
    @categories = Category.all
  end

  def show
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path(@category)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def new
    @category = Category.new
  end

  def destroy
    @category.destroy
    redirect_to categories_path
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/bookmarks/new.html.erb
<div class ="form-new mt-4">
<h1>Add new recipe to <%= @category.name %></h1>
<%= simple_form_for([@category, @bookmark])  do |f| %>
  <%= f.input :comment %>
  <%= f.association :recipe %>
  <%= f.button :submit, class: 'btn btn-warning' %>
<% end %>
</div>

app/views/categories/_navbar.html.erb
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= image_tag 'logo.png' %>
  <div class="collapse navbar-collapse" id="navbarText">
  <ul class="navbar-nav ms-auto">
      <li class = "nav-item"><%= link_to 'Home', root_path, class: "nav-link" %></li>
      <li class = "nav-item"><%= link_to 'New category', new_category_path, class: "nav-link" %></li>
  </ul>
    </div>
</nav>

app/views/categories/index.html.erb
<div class="card bg-dark text-white">
  <img class="card-img" src="https://freerangestock.com/sample/173651/modern-kitchen-with-tablet-recipe-holder.jpg" alt="Card image">
  <div class="card-img-overlay">
    <h4 class="card-title">Cookbook</h4>
    <p class="card-text">See your favourite recipes here!</p>
  </div>
</div>

<div class ="title-top">
<h3> Categories List</h3>
  <%= link_to 'New Category', new_category_path, class: "btn btn-warning" %>
</div>

<div class="cards mt-3">
  <% @categories.each do |category| %>
    <% if category.photo.attached? %>
      <div class="card-category", style ="background-image: url('<%=cl_image_path category.photo.key %>')">
        <div>
          <h2><%= link_to category.name, category_path(category), class:"category-link" %></h2>
          <p><%= category.recipes.count %> recipes</p>
        </div>
      </div>
    <% else %>
      <div class="card-category", style ="background-image: url('<%= image_path "food.jpeg"%>')">
        <div>
          <h2><%= link_to category.name, category_path(category), class:"category-link" %></h2>
          <p><%= category.recipes.count %> recipes</p>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/categories/new.html.erb
<div class ="form-new mt-4">
<h1>Create a new category</h1>
<%= simple_form_for [@category] do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit "Submit", class: 'btn btn-warning' %>
<% end %>
</div>

app/views/categories/show.html.erb
    <% if @category.photo.attached? %>
        <div class="card bg-dark text-white", style ="background-image: url('<%=cl_image_path @category.photo.key %>')">
          <div class="card-img-overlay">
            <h4 class="card-title"><%= @category.name %></h4>
          </div>
        </div>
    <% else %>
      <div class="card bg-dark text-white", style ="background-image: url('<%= image_path "food.jpeg"%>')">
       <h4 class="card-title"><%= @category.name %></h4>
      </div>
    <% end %>

<div class ="title-top">
<h2> Recipes</h2>
<h3><%= link_to 'Add a recipe', new_category_bookmark_path(@category), class: "btn btn-warning" %></h3>
</div>


<div class="cards">
 <% @category.bookmarks.each do |bookmark| %>
  <div class = "card-trip" >
    <img class="card-img-top" src="<%= asset_path(bookmark.recipe.image_url)%>" alt="Card image cap">

<%= link_to bookmark_path(bookmark),
    data: {
        turbo_method: :delete,
        turbo_confirm: "Are you sure you want to delete #{bookmark.recipe.name} from your #{@category.name} list?"
    },
    class: "btn-delete" do %>
    <i class="fa-solid fa-trash-can"></i>
<% end %>



     <div class="card-description">

      <h2><%= bookmark.recipe.name %></h2>
      <p><%= bookmark.recipe.description.truncate(400) %></p>
     </div>

     <div class ="card-trip-infos">
     <div>
     <p><%= bookmark.comment %></p>
     </div>

     <div>
     <%= bookmark.recipe.rating %> <%= '⭐' * bookmark.recipe.rating  %>
     </div>

     </div>
  </div>
 <% end %>
</div>
<%#
    <%= bookmark.recipe.name %> |

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsCookbook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'categories/navbar' %>
    <%= yield %>
  </body>
</html>